version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: flight_monitor_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=flight_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: flight_monitor_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: